name: YuZeXingHePlugin
version: '1.9.2'
main: com.yuzexingheplugin.YuZeXingHePlugin
api-version: '1.20'

softdepend:
  - PlaceholderAPI

commands:
  open:
    description: "插件的快捷UI界面"
  configs:
    description: "配置文件修改和加载相关指令"
  level:
    description: "提供玩家等级和排行等查询"
  levelconfig:
    description: "修改等级相关配置"