# 配置文件读取成功，发送给服务端
start: "配置文件读取成功！"
start_def: "您没有足够的权限或者配置文件出错！"
all_formulation_false: "自定义配方总开关已关闭！"
all_formulation_true: "自定义配方总开关已开启！"
registerRecipes_enchanted_golden_apple_false: "附魔金苹果配方已关闭！"
registerRecipes_enchanted_golden_apple_true: "附魔金苹果配方已开启！"
block_andesite_false: "安山岩配方已关闭！"
block_andesite_true: "安山岩配方已开启！"
block_granite_false: "花岗岩配方已关闭！"
block_granite_true: "花岗岩配方已开启！"
block_diorite_false: "闪长岩配方已关闭！"
block_diorite_true: "闪长岩配方已开启！"
# 设置自定义配方的开启关闭（打开all_formulation后下方的自定义配方内容才会生效）
all_formulation: true
registerRecipes_enchanted_golden_apple: true
block_andesite: true
block_granite: true
block_diorite: true