name: YuZeXingHePlugin
version: '${version}'
main: com.yuzexingheplugin.YuZeXingHePlugin
api-version: '1.20'

commands:
  ui:
    description: "YuZeXingHe-Plugin的第1条可用的指令方式"
    usage:
      - /ui <UIopen>
      - /ui <help>
      - /ui <config>
  yzxh:
    description: "YuZeXingHe-Plugin的第2条可用的指令方式"
    usage:
      - /yzxh <UIOpen>
      - /yzxh <help>
      - /yzxh <config>